### ISSUE TITLE
RegisterJaeger error in All services

### ISSUE THREAD

**Issue by vnexter** [devmentors/Pacco.Services.Customers#1]
Hi Guys, 

For all the services I am having issues with lines as below in Services.Infrastructure Extensions.cs

I just cloned and built with errors below.. 

.AddRabbitMq(plugins: p => p.RegisterJaeger())

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0411	The type arguments for method 'Extensions.AddRabbitMq<TContext>(IConveyBuilder, string, string, Func<IRabbitMqPluginRegister, IRabbitMqPluginRegister>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.	Pacco.Services.Customers.Infrastructure	C:\Users\MBS\Documents\GitHub\Pacco\scripts\Pacco.Services.Customers\src\Pacco.Services.Customers.Infrastructure\Extensions.cs	46	Active

Thanks in Advance.

**Comment by spetz** [comment]
Hey,
It's happening due to the changes in our [Convey](https://github.com/convey-stack) libraries - we've changed `AddRabbitMq()` extension to `AddRabbitMq<T>()` where T is the so-called correlation context, that can be any class defined on your own. In order to make it work (for now), you could either use the previous versions of Convey packages or wait (if it's ok for you) for 1-2 more days until we upgrade the overall solution :).

**Comment by vnexter** [comment]
Thank you for quick response, still learning so will wait for you guys! thanks again for great learning resource.

**Comment by spetz** [comment]
You're welcome, will let you know here once everything is updated!

**Comment by spetz** [comment]
All of the repositories have been updated, you should be able to pull the latest changes and build the solution without any issues :).
